#!/bin/sh
RunWeb=`/bin/get_key_value /etc/synoinfo.conf runweb`
RunMySQL=`/bin/get_key_value /etc/synoinfo.conf runmysql`
if [ ! -d /var/services/web -o "x$RunWeb" != "xyes" ]; then
	echo "Please enable Web Station first." > $SYNOPKG_TEMP_LOGFILE
	if [ -f /tmp/Joomla.upgrade ]; then
		/bin/rm /tmp/Joomla.upgrade
	fi
	exit 1
fi
if [ "x$RunMySQL" != "xyes" ]; then
	echo "Please enable MySQL first." > $SYNOPKG_TEMP_LOGFILE
	if [ -f /tmp/Joomla.upgrade ]; then
		/bin/rm /tmp/Joomla.upgrade
	fi
	exit 1
fi
VERSION=`/bin/get_key_value /etc.defaults/VERSION buildnumber`
if [ $VERSION -lt 1594 ]; then
	echo "The failed installation is due to the old-of-date firmware version." > $SYNOPKG_TEMP_LOGFILE
	echo "Please update to the latest firmware." >> $SYNOPKG_TEMP_LOGFILE
	if [ -f /tmp/Joomla.upgrade ]; then
		/bin/rm /tmp/Joomla.upgrade
	fi
	exit 1
fi

echo $pkgwizard_mysql_password > $$
pkgwizard_mysql_password=`sed 's/"/\\"/gp' $$`
/bin/rm -f $$

/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" -e "create database if not exists joomla";
if [ $? -eq "1" ]; then
	if [ -z $SYNOPKG_DSM_LANGUAGE ]; then
		echo "Can't create mysql database 'joomla' due to non-default mysql root password. Please use phpMyAdmin to create the database and go Joomla page to finish the installation process" > $SYNOPKG_TEMP_LOGFILE
		exit 0;
	fi
	case $SYNOPKG_DSM_LANGUAGE in
		chs)
			echo "请检查您的 MySQL 密码，然后再试一次。" > $SYNOPKG_TEMP_LOGFILE 
		;;
		cht)
			echo "請檢查您的 MySQL 密碼，然後再試一次。" > $SYNOPKG_TEMP_LOGFILE 
		;;
		csy)
			echo "Zkontrolujte heslo MySQL a zkuste to znovu." > $SYNOPKG_TEMP_LOGFILE 
		;;
		dan)
			echo "Kontroller din MySQL-adgangskode, og prøv igen." > $SYNOPKG_TEMP_LOGFILE 
		;;
		enu)
			echo "Please check your MySQL password and try again." > $SYNOPKG_TEMP_LOGFILE 
		;;
		fre)
			echo "Veuillez vérifier votre mot de passe MySQL et réessayer." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ger)
			echo "Prüfen Sie Ihr MySQL-Passwort und versuchen Sie es erneut." > $SYNOPKG_TEMP_LOGFILE 
		;;
		hun)
			echo "Ellenőrizze MySQL–jelszavát, majd próbálja újra." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ita)
			echo "Controllare la password MySQL e riprovare." > $SYNOPKG_TEMP_LOGFILE 
		;;
		jpn)
			echo "MySQL のパスワードを確認してもう一度行ってください。" > $SYNOPKG_TEMP_LOGFILE 
		;;
		krn)
			echo "MySQL 패스워드를 확인하고 다시 시도하십시오." > $SYNOPKG_TEMP_LOGFILE 
		;;
		nld)
			echo "Controleer uw MySQL-wachtwoord en probeer het opnieuw." > $SYNOPKG_TEMP_LOGFILE 
		;;
		nor)
			echo "Vennligst sjekk MySQL-passordet og prøv igjen." > $SYNOPKG_TEMP_LOGFILE 
		;;
		plk)
			echo "Sprawdź swoje hasło MySQL i spróbuj ponownie." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ptb)
			echo "Verifique sua senha MySQL e tente novamente." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ptg)
			echo "Verifique a sua palavra-passe do MySQL e tente novamente." > $SYNOPKG_TEMP_LOGFILE 
		;;
		rus)
			echo "Проверьте пароль MySQL и повторите попытку." > $SYNOPKG_TEMP_LOGFILE 
		;;
		spn)
			echo "Compruebe su contraseña de MySQL y vuelva a intentarlo." > $SYNOPKG_TEMP_LOGFILE 
		;;
		sve)
			echo "Kontrollera ditt MySQL-lösenord och försök igen." > $SYNOPKG_TEMP_LOGFILE 
		;;
		trk)
			echo "Lütfen MySQL parolanızı kontrol edin ve yeniden deneyin." > $SYNOPKG_TEMP_LOGFILE 
		;;
		*)
			echo "Check your MySQL password" > $SYNOPKG_TEMP_LOGFILE 
		;;
	esac
	if [ -f /tmp/Joomla.upgrade ]; then
		/bin/rm /tmp/Joomla.upgrade
	fi
	exit 1;
fi
/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" -e "GRANT ALL PRIVILEGES  ON joomla.* TO joomla@localhost"; 
/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" -e "FLUSH PRIVILEGES";


exit 0
