#!/bin/sh
if [ "$SYNOPKG_PKG_STATUS" ==  "UPGRADE" -o -f "/tmp/Joomla.upgrade" ]; then
	exit 0
fi

RunMySQL=`/bin/get_key_value /etc/synoinfo.conf runmysql`
if [ "x$RunMySQL" != "xyes" ]; then
	echo "Please enable MySQL first." > $SYNOPKG_TEMP_LOGFILE
	exit 1
fi

echo $pkgwizard_mysql_password > $$
pkgwizard_mysql_password=`sed 's/"/\\"/gp' $$`
/bin/rm -f $$

/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" --database=joomla -e "SELECT option_value FROM wp_options Where option_name='home'" > $$
if [ $? -eq "0" ]; then
    wp_home=`sed -n 's/http.*\/\/.*\/\(.*\)/\1/gp' $$`
    /bin/rm -rf /var/services/web/${wp_home}
fi


if [ "$pkgwizard_remove_mysql" != "true" ]; then
	exit 0
fi

/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" -e "DROP DATABASE joomla";
if [ $? -eq "1" ]; then
	if [ -z $SYNOPKG_DSM_LANGUAGE ]; then
		echo "But Joomla database remove unsuccessfully" > $SYNOPKG_TEMP_LOGFILE
		exit 0;
	fi
	case $SYNOPKG_DSM_LANGUAGE in
		chs)
			echo "然而，您无法删除 Joomla 数据库，因为密码输入错误。" > $SYNOPKG_TEMP_LOGFILE 
		;;
		cht)
			echo "然而，您無法刪除 Joomla 資料庫，因為密碼輸入錯誤。" > $SYNOPKG_TEMP_LOGFILE 
		;;
		csy)
			echo "Nemůžete však odstranit databázi Joomla kvůli špatnému heslu." > $SYNOPKG_TEMP_LOGFILE 
		;;
		dan)
			echo "Du kan dog ikke slette Joomla-databasen på grund af den forkerte adgangskode." > $SYNOPKG_TEMP_LOGFILE 
		;;
		enu)
			echo "However, you cannot delete the Joomla database due to the wrong password." > $SYNOPKG_TEMP_LOGFILE 
		;;
		fre)
			echo "Cependant, vous ne pouvez pas supprimer la base de données Joomla en raison du mot de passe erroné." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ger)
			echo "Die Joomla-Datenbank kann nicht gelöscht werden, weil das Passwort nicht korrekt ist." > $SYNOPKG_TEMP_LOGFILE 
		;;
		hun)
			echo "A Joomla–adatbázis viszont a rossz jelszó miatt nem törölhető." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ita)
			echo "Tuttavia, è impossibile eliminare il database Joomla a causa di password errata." > $SYNOPKG_TEMP_LOGFILE 
		;;
		jpn)
			echo "ただし、パスワードが正しくないので Joomla データベースを削除できません。" > $SYNOPKG_TEMP_LOGFILE 
		;;
		krn)
			echo "그러나 패스워드가 잘못되어 Joomla 데이터베이스를 삭제할 수 없습니다." > $SYNOPKG_TEMP_LOGFILE 
		;;
		nld)
			echo "U kunt de Joomla-database niet verwijderen als gevolg van het verkeerde wachtwoord." > $SYNOPKG_TEMP_LOGFILE 
		;;
		nor)
			echo "Du kan imildertid ikke slette Joomla-databasen på grunn av feil passord." > $SYNOPKG_TEMP_LOGFILE 
		;;
		plk)
			echo "Nie można usunąć bazy danych Joomla, ponieważ hasło jest nieprawidłowe." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ptb)
			echo "Contudo, você não pode excluir o banco de dados do Joomla por causa da senha incorreta." > $SYNOPKG_TEMP_LOGFILE 
		;;
		ptg)
			echo "No entanto, não pode eliminar a base de dados Joomla devido à palavra-passe errada." > $SYNOPKG_TEMP_LOGFILE 
		;;
		rus)
			echo "Однако вы не сможете удалить базу данных Joomla из-за неверного пароля." > $SYNOPKG_TEMP_LOGFILE 
		;;
		spn)
			echo "No obstante, no puede eliminar la base de datos de Joomla por ser errónea la contraseña." > $SYNOPKG_TEMP_LOGFILE 
		;;
		sve)
			echo "Du kan dock inte radera Joomla databas på grund av fel lösenord." > $SYNOPKG_TEMP_LOGFILE 
		;;
		trk)
			echo "Ancak, yanlış parola yüzünden Joomla veritabanını silenezsiniz." > $SYNOPKG_TEMP_LOGFILE 
		;;
		*)
			echo "But Joomla database remove unsuccessfully" > $SYNOPKG_TEMP_LOGFILE 
		;;
	esac
	exit 0;
fi
/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" -e "DROP USER joomla@localhost";
/usr/syno/mysql/bin/mysql -u root --password="${pkgwizard_mysql_password}" -e "FLUSH PRIVILEGES";


exit 0
